### ISSUE TITLE
Pakistan Meteorological Department (PMD)

### ISSUE THREAD

**Issue by aaarendt** [NASA-Planetary-Science/HiMAT#19]
* these are available but are not free
* there are significant discounts for purchasing them for research purposes

**Comment by aaarendt** [comment]
* Jawairia is a good contact, via Bart

**Comment by aaarendt** [comment]
* Bruce will check to see if PMD = WAPDA

**Comment by aaarendt** [comment]
* Bart and Jawairia have provided ordering info to UW to get 5 high elevation stations
* UW is processing order/getting permission
* we need all of the team to sign a usage constraint form

**Comment by aaarendt** [comment]
Forms are signed and order has been submitted by UW purchasing. Awaiting delivery of the data.

**Comment by aaarendt** [comment]
Data ordered, Jawairia is checking on the status.

**Comment by aaarendt** [comment]
Data arrived, Don is cleaning. Bruce is setting up FTP site for secure distribution via NSIDC.

**Comment by lsetiawan** [comment]
This has been accomplished. All data is in secure FTP site distributed by NSIDC.
