### ISSUE TITLE
modifications to MODSCAG NetCDF conversion code

### ISSUE THREAD

**Issue by aaarendt** [NASA-Planetary-Science/HiMAT#39]
- [x] replace all values of 235 by the FillValue.
- [x] add the time dimension (as a "record dimension")
- [x] rename coordinates and dimensions from x / y to lon / lat
- [x] `ds.sortby('y')` was needed so I could do plots in xarray/cartopy. At least xarray didn't like the inverted order in the coordinates (it explains why we kept getting blank output when plotting)
- [x] we don't need to retain 2D lat/long grids. That reduced file size by a lot 
- [x] convert March 19, 2008 geotiff to NetCDF (currently in /att/nobackup/aarendt)

**Comment by lsetiawan** [comment]
Resolved by #46. Closing.
