### ISSUE TITLE
EC2 Instance(s) to support U-Utah WRF runs

### ISSUE THREAD

**Issue by aaarendt** [NASA-Planetary-Science/HiMAT#40]
* @adamk0 and @robfatland are discussing technical needs
* @atlehr and @lsetiawan to assist in instantiating the EC2 instances

**Comment by robfatland** [comment]
https://www.gitbook.com/book/phirov/deploy-wrf-at-aws/details looks like a recipe resource.

Adam quotes 100,000 core hours per simulation year; goal is to do 7 years. 

On AWS the EC2 instance c4.8xlarge features 18 cores (2 vCPUs each) at $1.60 per hour but this is reduced on the spot market to $0.50 per hour. 

For all 7 years: $19k or $2800 per simulation year. I suggest obviously running one year to see what the actual cost proves to be.

**Comment by amanda-tan** [comment]
We can also look into using EnginFrame to provision the runs.

**Comment by aaarendt** [comment]
Thanks for moving this forward - will meet with Amanda and Don tomorrow and will figure out costs. Stay tuned...

**Comment by aaarendt** [comment]
- [ ] @atlehr to test implementing WRF on multiple clusters on AWS. Some resources [here](https://www.gitbook.com/book/phirov/deploy-wrf-at-aws/details)

**Comment by aaarendt** [comment]
Closing as I haven't seen any movement on this in a few months.
