### ISSUE TITLE
issue with MODSCAG data

### ISSUE THREAD

**Issue by aaarendt** [NASA-Planetary-Science/HiMAT#70]
From Bob Rosenberg: 
I just wanted to let you know that I have essentially completed gridding and stitching together the MODSCAG snow data.  Now I am now working on doing the same with the MODDRFS grain size data, and have discovered that some of the tiles in the HiMAT region were created differently from the others.   Most tiles fit the documentation in terms of what the numbers should be, but then there are a few that have numbers that do not match, and also contain a mixture of intergers and reals in the same “Band1” field, which I have not encountered before.   For those, the integers do not correspond with the documentation.

I will include below the links to one of each case for you to look at, if you have the time.   I will include the original .tif file, the .nc file that I made using "GDAL translate”, and a dump of the header and Band1 for the corresponding .nc file.   I will note that I noticed one difference in the headers, namely in the line that contains ":GDAL_TIFFTAG_DOCUMENTNAME =……”.   The ones that have "./MOD09GA……..tif” look correct, while the ones with that line containing :  "/clusterfs/output/MODDRFS/1344210065493/MOD09GA…..tif” are different and not cosistent with the documentation.   Seems like the first was originally a local file, while the second was on a server somewhere (maybe a big/little endian issue or something like that?)

So far I have found this with years 2001 and 2002, and have not checked other years yet, but will.   Here are the paths to the abovementioned sample files:

One that looks correct:
———————————————
/discover/nobackup/projects/lis_hma/users/rirosenb/MODDRFS/historic/data/MOD09GA.A2002100.h22v04.005.2008293201726.drfs.grnsz.tif
/discover/nobackup/projects/lis_hma/users/rirosenb/MODDRFS/historic/data/MOD09GA.A2002100.h22v04.005.2008293201726.drfs.grnsz.nc
/discover/nobackup/projects/lis_hma/users/rirosenb/MODDRFS/historic/data/MOD09GA.A2002100.h22v04.005.2008293201726.drfs.grnsz.nc.dump

One that does not:
————————————
/discover/nobackup/projects/lis_hma/users/rirosenb/MODDRFS/historic/data/MOD09GA.A2001100.h23v05.005.2007011120328.drfs.grnsz.tif
/discover/nobackup/projects/lis_hma/users/rirosenb/MODDRFS/historic/data/MOD09GA.A2001100.h23v05.005.2007011120328.drfs.grnsz.nc
/discover/nobackup/projects/lis_hma/users/rirosenb/MODDRFS/historic/data/MOD09GA.A2001100.h23v05.005.2007011120328.drfs.grnsz.nc.dump

**Comment by lsetiawan** [comment]
@aaarendt Based on the filepath, these stuff seems to be in `/discover`, which I don't think we have access to. Thanks.
