### ISSUE TITLE
HMA basins

### ISSUE THREAD

**Issue by aaarendt** [NASA-Planetary-Science/HiMAT#73]
@lsetiawan we acquired HMA watershed basins when I made the HiMAT AGU poster. Can you help me find those again and we can post to HiMAT google shared drive. Thanks!

**Comment by lsetiawan** [comment]
@aaarendt It's in Google Drive. `Nasa High Asia/shp/HydroSheds` and the shapefile name should be called `Basin_boundary.shp`
