### ISSUE TITLE
GRACE_water_balance_validation.ipynb needs to update

### ISSUE THREAD

**Issue by hydrogeohc** [NASA-Planetary-Science/HiMAT#84]
Apparently, the spatial trend plot for GRACE is wrong. I don't know if I can revise this notebook myself since I don't have access to AWS or any zarr stuff in the beginning of notebook.

**Comment by aaarendt** [comment]
I have rerun the notebook with the repaired himatpy, so the trend map is now correct. 
I ran this in a new instance of Pangeo where I could deploy dask workers as needed.
